### ISSUE TITLE
kubectl service unavailable?

### ISSUE THREAD

**Issue by elchmartin** [ct-Open-Source/team-container#1]
hi there.

i just tried installing the server as mentioned in ct9/2020.
my (v-)server is runnign ubuntu 16.04.6 LTS.
did the git clone and install.sh, did a reboot. all fine so far.

then theres the issue I am facing:

`root@myserver:~/team-container# kubectl get nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request
root@myserver:~/team-container# kubectl get nodes
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
root@myserver:~/team-container# kubectl get nodes
error: the server doesn't have a resource type "nodes"
root@myserver:~/team-container# kubectl get nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes)
root@myserver:~/team-container# kubectl get nodes
No resources found in default namespace.`

the port 6443 does not seem to be open (ran a open port check from the server itself)
what am I missing?

**Comment by calingit** [comment]
Nearly the same here: Debian Buster, after reboot and testing kubernetes with typing "kubectl get nodes" getting: "The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?"

Tried it twice on fresh installs with Ubuntu LTS 18.04. and Debian Buster.

**Comment by elchmartin** [comment]
i will try on ubuntu 19.10 server in a few moments - keeping my fingers crossed, maybe it is my 16.04 version ... but we'll see.

**Comment by calingit** [comment]
@elchmartin how'd it go?

**Comment by guetler** [comment]
I got the same error on a VPS (18.04) from a hosting provider. it worked without problems with a VPS (18.04) from another provider... / local installation on 18.04 vm also worked perfectly.

**Comment by elchmartin** [comment]
> @elchmartin how'd it go?

a little better, thus not really working. got some 404 error .. .but maybe my subdonmains were wrong.
resetting my installation - might again take a little while.

**Comment by jamct** [comment]
We tested it with virtual machines with different hosters (mostly on ubuntu server).
Maybe we should create table to document the compatibility.
Maybe some hosters did some unusual network configuration.

**Comment by jamct** [comment]
I just added a wiki page:
https://github.com/ct-Open-Source/team-container/wiki/Compatibility

**Comment by elchmartin** [comment]
OK now I reset ubuntu (19.10server), set up my domain name correctly and am now getting a "welcome to nginx"-page with a valid LetsEncrypt-certificate. Need to wait a few minutes according to the article, lets see ;-)
I will report if it works, maybe it can be added to the wiki then.

**Comment by calingit** [comment]
I've been trying all afternoon: Ubuntu LTS 18.04, Debian Buster, Ubuntu 19.04. Always fresh installations on a VPS from euserv.com. 
I always get the error "**The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?**
The hosts-file looks like this:

**127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
2a02:0180:0006:0001:0000:0000:0000:XXXX srvXXXX.blue.kundencontroller.de srvXXXX
81.7.17.XXX srvXXXXX.blue.kundencontroller.de srvXXXX**

Does anyone have any other ideas? I can't get any further here and I can't find any hints on the net with this error pattern.

**Comment by guetler** [comment]
i've had the same problems - the problem seems to be in some hosting-provider's network configuration. no chance to get it up and running... tried a different provider - all ok now.

**Comment by elchmartin** [comment]
so now I installed nextcloud, chat and video, all installed without error.
BUT I do not get anything else but the nginx-welcome when I browser to "cloud.#myserver#.de".
however, "video.#myserver#.de" and "chat.#myserver#.de" work fine. what did I miss there?
another issue is that i would really like to password-protect the jitsi-server - dont want to wait for the next c't ;-) but that should be covered in another issue here o github i guess,

**Comment by elchmartin** [comment]
nevermind, I had a flaw in my values-nextcloud.yaml configuration.
thankfully I made a snapshot just before - so everything works as described.
for now i will leave the jitsi disabled until i can figure out access restrictions.

this is why I will close my issue for now.

My config:
Ubunutu 19.10 running on:
https://contabo.de/?show=konfigurator&vserver_id=206
maybe someone can add it to the wiki.

**Comment by jamct** [comment]
Added to [compatibility list](https://github.com/ct-Open-Source/team-container/wiki/Compatibility).

**Comment by anotherHoffmann** [comment]
Do you have any information about Strato V-Servers?
