### ISSUE TITLE
Jitsi - Locking Conference Creation

### ISSUE THREAD

**Issue by Groess** [ct-Open-Source/team-container#10]
**I was wondering if it is possible to implement a User - Password protection for the room creation in Jitsi.** 
If I´m not miss informed, everybody who knows the webadress can create a room and I as owner can´t even see if there was a room created by a stranger or not.

There is a tutorial at Digital Ocean for Jitsi Meet ( https://do.co/2KaFCtE ) with such an authorisation step ( Step 5 in the tut). But I can´t find this files in this container to edit them, (noob ;-)

(is there a possibility to see the rooms which are active as admin)

**Comment by jamct** [comment]
Hi @Groess,
there are a lot of questions on how to configure Jitsi. I will work on this topic this week. Password protection and administration is possible!

**Comment by KL64** [comment]
Password-protection for room-creation would be really great - thanks in advance.

**Comment by sirrus** [comment]
Password protection has been added - I've added ldap - please review my pull request.

**Comment by jamct** [comment]
@sirrus Do you have an LDAP test environment?
I think, I found another issue on this problem: [LDAP does not even try (jitsi/docker-jitsi-meet)](https://github.com/jitsi/docker-jitsi-meet/issues/285#issuecomment-606903362).
Do you see any LDAP connections on your ldap server logs?

**Comment by sirrus** [comment]
I'm checking the logs later - Authentication works (as a wrong credendital will be blocked).
I'ts stuck on Connecting to the room...

**Comment by sirrus** [comment]
@jamct It seems to be realted...
```
Jicofo 2020-06-11 23:52:33.223 INFO: [31] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: muc.video.commeo-law.com, null
Jicofo 2020-06-11 23:52:33.223 INFO: [31] org.jitsi.jicofo.JitsiMeetServices.log() MUC component discovered: muc.video.commeo-law.com
Jicofo 2020-06-11 23:52:33.224 SEVERE: [31] org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.log() Failed to discover features for conferenceduration.video.commeo-law.com: XMPP error reply received from conferenceduration.video.commeo-law.com: XMPPError: service-unavailable - cancel
Jicofo 2020-06-11 23:52:33.226 INFO: [31] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: internal-muc.video.commeo-law.com, null
Jicofo 2020-06-11 23:52:33.226 INFO: [31] org.jitsi.jicofo.ComponentsDiscovery.log() Service rediscovery disabled
Jicofo 2020-06-11 23:52:33.226 INFO: [31] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered
Jicofo 2020-06-11 23:52:33.238 INFO: [31] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() XMPP provider Jabber:focus@auth.video.commeo-law.com/focus36885293381@video-team-video-prosody connected (JID: focus@auth.video.commeo-law.com/focus36885293381)
```

**Comment by sirrus** [comment]
I've solved it!
You can find my pull request here: https://github.com/ct-Open-Source/team-container/pull/39

**Comment by chjohn22** [comment]
@Groess Looks like you can close this issue.
