### ISSUE TITLE
Error: Kubernetes cluster unreachable

### ISSUE THREAD

**Issue by trevor87** [ct-Open-Source/team-container#13]
After running the setup script I got the message:

`Error: Kubernetes cluster unreachable`

To fix it I used the command 

` export KUBECONFIG=/etc/rancher/k3s/k3s.yaml`

Edit: It worked, but I am not sure if this is the appropriate solution, as there is some default password in this file.

**Comment by jamct** [comment]
It is the correct way. After running instal.shl you have to restart or logout and login again (the script says it at the end too).
