### ISSUE TITLE
How to needed: running several services behind one MyFRITZ! domain?

### ISSUE THREAD

**Issue by pagong** [ct-Open-Source/team-container#16]
While porting the `team-container` project to [k3os](https://github.com/pagong/jitsi-meet-on-k3os) for a home network, I've come across a limitation of my _(all?)_ `FRITZ!Boxes`. The current implementation of `team-container` needs a separate FQDN for each service, e.g. Nginx, Nextcloud, Rocket and Jitsi.

But there is only one port forwarding possible with the built-in dynamic DNS `MyFritz!` domain name. So all HTTP and HTTPS traffic arrives at the `Traefik2` router with the same external FQDN.

What needs to be changed in the `IngressRoute` objects of the `team-container` sub-projects, to use path-based routing with `Traefik2`, instead of fqdn-based routing?

Example: I need a solution how to change `video.example.com` to `xxyyzz.myfritz.net/video`
and `chat.example.com` to `xxyyzz.myfritz.net/chat`, etc.

**Comment by merlinschumacher** [comment]
If you own an external domain name, you could create multiple CNAME subdomain entries for the Myfritz-address.

**Comment by pagong** [comment]
In the mean time, I've discovered this [section ](https://docs.traefik.io/migration/v1-to-v2/#strip-and-rewrite-path-prefixes) in the docs for `Traefik2`, which looks rather promising.
I'll report back, when I've got this working with `team-container`.

**Comment by kaffeetas** [comment]
just use a dynamic DNS provider that supports wildcard domains like twodns.de does.

**Comment by pagong** [comment]
OK, I've given up on trying to use path based routing for `jitsi-meet` with `myfritz.net`.
I've followed the recommendation and switched to using the wildcard domain feature of dynamic DNS provider `twodns.de`. That's working great. 

Now I just need to update the `team-video` chart to the newest c't version.
