### ISSUE TITLE
Black Screen in Jitsi

### ISSUE THREAD

**Issue by Harpau** [ct-Open-Source/team-container#22]
On an Ubuntu Server 18.04 LTS I have successfully installed the complete team server. Only Jitsi doesn't work: During a video call, the person I'm talking to and I see the image of our own cameras, but we can neither see nor hear each other.

**Comment by elchmartin** [comment]
you closed the issue - what did you change, does it work now? i have the same problem right now - upgraded my server to ubuntu 20.04 LTS and updated to password-protected setup (as described in the current (12/2020) ct-magazine...

**Comment by Harpau** [comment]
Ich hoffe, es ist in Ordnung, wenn ich auf deutsch antworte. Ich habe lediglich den Provider gewechselt und nun einen aus der Kompatibilitätsliste (Contabo) genommen. Damit hat es auf Anhieb funktioniert. Der Server läuft unter Ubunto 20.04. Die In der neuen ct beschriebenen Änderungen habe ich jedoch noch nicht durchgeführt.

**Comment by elchmartin** [comment]
Für mich kein Problem - But I think it is preferred to keep writing in english ;-)

the contabo compatibility report came from me :D but still with the new additions it does not really work, even after reinstalling the whole thing (ubuntu 20.04LTS and team-container)... well let us see

**Comment by Harpau** [comment]
Sorry for the delay in my answer. When you wrote me, I tested it again (with the new addition only for user login) and I had the "black screen" issue again! Yesterday I tested it at home instead in my office as I did for the first test - and it worked well! The difference is the firewall. At home I'm using a Fritz!Box, in the office we have a professional firewall. If you would like to do so, we can make a test call using my installation.

**Comment by elchmartin** [comment]
No problemo :) 

Yeah we could try that, maybe it's the Fritzbox I use at home, too. 
Fun thing is that it worked from home before with the 'old' installation....

**Comment by Harpau** [comment]
With the FritzBox it is working without any issues. In the meantime I got opened UDP Port 30000 in my office and now its working fine there as well.

**Comment by Harpau** [comment]
If you are interested in doing further investigations, e.g. a test call, please contact me directly on ct-temp@taskflow.de
