### ISSUE TITLE
After  update Nextcloud is completely broken when trying to update iself to version 21.03

### ISSUE THREAD

**Issue by Tomtiger66** [ct-Open-Source/team-container#69]
After installing an update of my nextcoud-server the server needs to reboot. After reboot Nextcloud shows the maintaince-mode. After editing the the `/var/lib/rancher/k3s/storage/pvc-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/config/config.php ` and setting ` 'maintenance' => false,` 

After reloading Nextcloud shows an update screen: 

### **Nextcloud wird auf Version 21.0.3 aktualisiert**
Folgende Apps werden aktualisiert:

-     Accessibility (accessibility)
-------------snipped---------------------
-     Nextcloud workflow engine (workflowengine)

Diese inkompatiblen Apps werden deaktiviert:

-     Announcement center (announcementcenter)
-------------snipped---------------------
-     Workflow OCR (workflow_ocr)

### **Aktualisierung starten**

After klicking the start-Button you get an error-message.

### **Aktualisierung auf 21.0.3**
Exception: Database error when running migration latest for app core

> Detaillierte Protokollmeldungen

> Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.
![grafik](https://user-images.githubusercontent.com/11893256/126878529-c38d09b9-38e3-4333-ba42-b8cb32ddb2a3.png)

After reloading the page you get the update-screen again. You can try as many times as you want, the update will fail. 

The reason seems to be that the new docker-image pulled by kubernets got an update of the used maria-db-image. 
The problem is described here: #https://github.com/nextcloud/docker/issues/1536
So one has to 
1. lock the used maria-db version to 10.5 in the helm charts or 
2. converting the row format of the tables of the Nextcloud database: [https://github.com/nextcloud/docker/issues/1492](url)
3. ad a line` innodb_read_only_compressed=OFF` to the section` [mysqld]` to the file: /etc/my.cnf.d/server.cnf
I prefer the first or third solution. So: who knows to lock the mariadb verion inside the helm-charts or howto ad ` innodb_read_only_compressed=OFF` to the server.cnf?

Thank you
Thomas

**Comment by jamun53** [comment]
Hi Thomas,
Thanks for the advice!
this means that my Nextcloud will no longer work as soon as I restart the server? In the meantime, have you found a solution to this problem?

**Comment by Tomtiger66** [comment]
Hallo, yes, I have. Because the developers are actuelly discussing to change the default row format of the nextcoud databases from compressed to dynamic I decided to convert the database and the default nextcloud row format to dynamic. 
Here are the steps: 

1. For your own security make a  full backup of your nextcloud-installation that is restorable anywhere you want. For this you have to backup **a)** the data-directory **b)** the configuration-file **c)** the data-base. If you do not yet have a directory for your backups create on,  for example `mkdir ~/Backup`. This will create the directory Backup inside your home directory. 

**a) - storage-directory:** and **b) the configuration-file**
1. `cd /var/lib/rancher/k3s/storage`
2.  ` ls -all` to find out where kubernets has putted your files and database from your nextcloud-installation. The data-directory is owend by www-data. The foldername is made up of a long chain of random characters. So enter the directory owend by www-data: `cd pvc-<xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx>` 
3. `sudo su` and your password to become root. Now set your Nextcloud to maintaince mode by opening the config/config.php file using the text-editor of your choice, searching `'maintenance' => false,` and change it to` 'maintenance' => true,`
4. `tar czvpf /home/<name-of-your-home-directory>/Backup/`date +"%d-%m-%Y"`-nextcloud-data.tar.gz data/* config/config.php` Using this command you will get an archive named dd-mm-yyyy-nextcloud-data.tar.gz
5. `exit` With exit you will exit the root-mode and be the normal user again. 

**c) Back up the database:** For this you have to enter the pod containing the database. 
1. Use  `cd /var/lib/rancher/k3s/storage` to enter the storage directory of kubernets again. 
2. Do  ` ls -all` again and `cd` to the folder owend by systemd-xxxxx
3. Enter the database pod: 
3.1. `kubectl get pods |grep nextcloud-db`  to show the name of the pod used for the following command
3.2 `kubectl exec -it nextcloud-team-nextcloud-db-xxxxxxxxxx-xxxxx -- /bin/bash`
4. Save your database to a single dump file: `mysqldump --single-transaction -h localhost -u nextcloud -p<your-very-secret-database-password-from-values-nextcloud.yaml> nextcloud > /var/lib/mysql/`date +"%d-%m-%Y"`-nextcloud-DB.sql`
5. `exit` to leave the database pod. 
5. `sudo su`  to be root again. Assuming you are still in the folder pvc-xxxxx containing your database you can now convert the row format of the tables in your database. 
6.` cat  *nextcloud-DB.sql | sed -e 's/ROW_FORMAT=COMPRESSED/ROW_FORMAT=DYNAMIC/'  | sed -e '/ROW_FORMAT/!s/^) ENGINE=InnoDB/) ENGINE=InnoDB ROW_FORMAT=DYNAMIC/' > nextcloud_db-mod.sql`
After this do mv  `*nextcloud-DB.sql ~/Backup` to compleate your Backup of your nextcloud.
7. `Exit `to the normal user. and enter the database pod again (repeat step 3)
8. Restore your database using the modified sql-dump file: 
```
mysql -h localhost -u nextcloud -p<your-very-secret-database-password-from-values-nextcloud.yaml> -e "DROP DATABASE nextcloud" 
mysql -h localhost -u nextcloud -p<your-very-secret-database-password-from-values-nextcloud.yaml> -e "CREATE DATABASE nextcloud"
mysql -h localhost -u nextcloud -p<your-very-secret-database-password-from-values-nextcloud.yaml> nextcloud < /var/lib/mysql/nextcloud_db-mod.sql
```
8. `exit `to leave the pod again
9. Reboot your server: `sudo shutdown -r now`
10. After reboot set the default row format in the Nextcloud configuration to dynamic: sudo `vi /var/lib/rancher/k3s/storage/pvc-<name-to-the-folder-owend-by-www-data>/lib/private/DB/ConnectionFactory.php` Go to row 228 inside the file and change  ` 'row_format' => 'compressed',` to `'row_format' => 'dynamic'`,

11. Now you can swich of the maintaince mode and do the update. If it will fail, go to the folder custom_apps and do as root
`mv mail  home<name-of-your-home-directory>/Backup` and start the update again.

**Comment by konwin** [comment]
You habe to change
`image: mariadb`
to
`image: mariadb:10.5`
in
`/blob/master/team-nextcloud/templates/deploy_database.yaml`
To lock mariadb to Version 10.5.

**Comment by Tomtiger66** [comment]
@konwin Thank you, I tried it with an other installation, to lock mariadb version 10.5 worked for me too.
