### ISSUE TITLE
nextcloud database initialization error

### ISSUE THREAD

**Issue by Wollipolli** [ct-Open-Source/team-container#70]
After following the instructions (setup+nextcloud), I get the following error in the nextcloud web-setup:

`Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE. `

Can anyone help me?

**Comment by konwin** [comment]
try to change
`image: mariadb`
to
`image: mariadb:10.5`
in
`/blob/master/team-nextcloud/templates/deploy_database.yaml`
as there is a problem with the latest mariadb:10.6 when using nextcloud!

**Comment by Wollipolli** [comment]
Thanks! That did the trick. 
Should be included in the repo.
